# Word Embedding using keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
##sentence
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer']

In [4]:
##vocabilary size
voc_size=10000

# One hot representation

In [5]:
one_hot_representation = [one_hot(word,voc_size) for word in sent]
print(one_hot_representation)

[[3135, 4946, 188, 471], [3135, 4946, 188, 4856], [3135, 2275, 188, 3111], [8915, 6780, 4009, 6977, 8323], [8915, 6780, 4009, 6977, 5067]]


# Word Embedding Representation

In [10]:
import keras
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
##padding sequencecs
sent_len=10
embedded_docs = pad_sequences(one_hot_representation,maxlen=sent_len,padding='pre')
print(embedded_docs)

[[   0    0    0    0    0    0 3135 4946  188  471]
 [   0    0    0    0    0    0 3135 4946  188 4856]
 [   0    0    0    0    0    0 3135 2275  188 3111]
 [   0    0    0    0    0 8915 6780 4009 6977 8323]
 [   0    0    0    0    0 8915 6780 4009 6977 5067]]


In [9]:
##dimensions
dim=10

In [13]:
##create Embedding layers
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
model.compile(optimizer='adam',loss=keras.losses.mean_squared_error)

In [14]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 10)            100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126
    0.00801792  0.02548062  0.0164845   0.04886503  0.03349752]
  [ 0.02549    -0.02565862  0.02881164  0.04277135  0.03577807
    0.01276108  0.00165186  0.00698232  0.01837317  0.03901603]
  [ 0.04066843 -0.02975835 -0.02076658 -0.04050493 -0.02059989
    0.02777796  0.03020085 -0.0190243   0.044710

In [18]:
##before representation
print(embedded_docs[0])

[   0    0    0    0    0    0 3135 4946  188  471]


In [17]:
##har ek word ki representation 10 dimensions mai hogyi
print(model.predict(embedded_docs)[0])

[[-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [-0.02290612  0.00012429 -0.02395008 -0.01202513  0.04738126  0.00801792
   0.02548062  0.0164845   0.04886503  0.03349752]
 [ 0.02549    -0.02565862  0.02881164  0.04277135  0.03577807  0.01276108
   0.00165186  0.00698232  0.01837317  0.03901603]
 [ 0.04066843 -0.02975835 -0.02076658 -0.04050493 -0.02059989  0.02777796
   0.03020085 -0.0190243   0.0447103   0.00696687]
